services:
  zookeeper-service:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper-container
#    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka_network

  kafka-service:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-container
#    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-service:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper-service
    networks:
      - kafka_network

networks:
  kafka_network:
    driver: bridge
