spring:
  application:
    name: content-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: event-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.content.model.dto"
        spring.json.value.default.type: "com.content.model.dto.EventDto"
    topic: eventdto-topic
    group-id: event-consumer-group

server:
  port: 8180
