spring:
  application:
    name: content-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.content.model.dto"
        spring.json.value.default.type: "com.content.model.dto.EventDto"
        reconnect.backoff.ms: 1000
        reconnect.backoff.max.ms: 50000
      group-id: event-consumer-group
      auto-offset-reset: earliest
      auto-startup: false
    topic: event-topic
#    listener:
#      ack-mode: manual
  datasource:
    #    url: jdbc:postgresql://postgres-service:15432/${POSTGRES_DB}
    url: jdbc:postgresql://localhost:15432/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update

server:
  port: 18080

api:
  version: v1

#logging:
#  level:
#    root: debug

image:
#  path: /event-image
  path: /Users/styner/0main/event-image
  file-name: _image
